sudo: required
services:
  - docker

before_install:
  - docker image build --tag juliocesarmidia/ipv6-converter-api .

script:
  - docker container run -d --name ipv6-converter-api -p 8080:8080 juliocesarmidia/ipv6-converter-api
