sudo: required
services:
  - docker

before_install:
  - docker image build --tag juliocesarmidia/ipv6-converter-api -f Dockerfile .

script:
  - docker container run -d --name ipv6-converter-api -p 5000:5000 juliocesarmidia/ipv6-converter-api
