version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - netlocal

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: Dockerfile-docs
    ports:
      - 5000:5000
    environment:
      - HOST:docs
      - PORT=5000
      - TARGET_HOST=api
      - TARGET_PORT=8080
    restart: always
    networks:
      - netlocal
    depends_on:
      - api

networks:
  netlocal:
    driver: bridge