version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - netlocal

networks:
  netlocal:
    driver: bridge