version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - HOST=api
      - PORT=5000
    restart: always
    networks:
      - netlocal

  docs:
    container_name: docs
    build:
      context: .
      dockerfile: Dockerfile-docs
    volumes:
      - /app/node_modules
      - ./swagger-docs:/app
    ports:
      - 8000:8000
    environment:
      - HOST=docs
      - PORT=8000
      - TARGET_HOST=api
      - TARGET_PORT=5000
    restart: always
    networks:
      - netlocal
    depends_on:
      - api

networks:
  netlocal:
    driver: bridge