openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'IPv6 Converter API Specification'
  description: 'IPv6 Converter API Specification'

security: 
  - application:
    - read
    - write

paths: 
  /api/v1/convert:
    parameters:
      - in: query
        name: ip
        schema:
          type: string
          example: ffff-ffff-ffff-ffff
        description: The IPv6 prefix
      - in: query
        name: mac
        schema:
          type: string
          example: ff-ff-ff-ff-ff-ff
        description: The MAC Address

    get:
      summary: Get the whole IPv6 formed with the given prefix and Mac Address
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        400:
          description: Bad Request
        500:
          description: Internal Server Error

components:
  schemas:
    body_response:
      type: object
      required: 
        - message
      properties:
        message:
          type: string
          description: The message returned from server
          example: '2804:ffff:ffff:ffff:ffff:ffff:ffff:ffff'